package org.transformice.luapi.functions.tfm;

// Imports
import org.luaj.vm2.LuaBoolean;
import org.luaj.vm2.LuaTable;
import org.luaj.vm2.LuaValue;
import org.luaj.vm2.lib.TwoArgFunction;
import org.transformice.Application;
import org.transformice.Room;

// Lua api
import org.transformice.luapi.functions.system.SY_bindKeyboard;
import org.transformice.luapi.functions.ui.UI_setMapName;
import org.transformice.luapi.functions.ui.UI_setShamanName;

public class LUA_TABLE_TFM extends TwoArgFunction {
    private final Room room;

    public LUA_TABLE_TFM(Room room) {
        this.room = room;
    }

    @Override
    public LuaValue call(LuaValue name, LuaValue table) {
        table.set("tfm", new LuaTable());
        table.get("tfm").set("enum", new LuaTable());
        table.get("tfm").get("enum").set("emote", new LuaTable());
        table.get("tfm").get("enum").get("emote").set("dance", 0);
        table.get("tfm").get("enum").get("emote").set("laugh", 1);
        table.get("tfm").get("enum").get("emote").set("cry", 2);
        table.get("tfm").get("enum").get("emote").set("kiss", 3);
        table.get("tfm").get("enum").get("emote").set("angry", 4);
        table.get("tfm").get("enum").get("emote").set("clap", 5);
        table.get("tfm").get("enum").get("emote").set("sleep", 6);
        table.get("tfm").get("enum").get("emote").set("facepaw", 7);
        table.get("tfm").get("enum").get("emote").set("sit", 8);
        table.get("tfm").get("enum").get("emote").set("confetti", 9);
        table.get("tfm").get("enum").get("emote").set("flag", 10);
        table.get("tfm").get("enum").get("emote").set("marshmallow", 11);
        table.get("tfm").get("enum").get("emote").set("selfie", 12);
        table.get("tfm").get("enum").get("emote").set("highfive", 13);
        table.get("tfm").get("enum").get("emote").set("highfive_1", 14);
        table.get("tfm").get("enum").get("emote").set("highfive_2", 15);
        table.get("tfm").get("enum").get("emote").set("partyhorn", 16);
        table.get("tfm").get("enum").get("emote").set("hug", 17);
        table.get("tfm").get("enum").get("emote").set("hug_1", 18);
        table.get("tfm").get("enum").get("emote").set("hug_2", 19);
        table.get("tfm").get("enum").get("emote").set("jigglypuff", 20);
        table.get("tfm").get("enum").get("emote").set("kissing", 21);
        table.get("tfm").get("enum").get("emote").set("kissing_1", 22);
        table.get("tfm").get("enum").get("emote").set("kissing_2", 23);
        table.get("tfm").get("enum").get("emote").set("carnaval", 24);
        table.get("tfm").get("enum").get("emote").set("rockpaperscissors", 25);
        table.get("tfm").get("enum").get("emote").set("rockpaperscissors_1", 26);
        table.get("tfm").get("enum").get("emote").set("rockpaperscissors_2", 27);
        table.get("tfm").get("enum").set("shamanObject", new LuaTable());
        table.get("tfm").get("enum").get("shamanObject").set("arrow", 0);
        table.get("tfm").get("enum").get("shamanObject").set("littleBox", 1);
        table.get("tfm").get("enum").get("shamanObject").set("box", 2);
        table.get("tfm").get("enum").get("shamanObject").set("littleBoard", 3);
        table.get("tfm").get("enum").get("shamanObject").set("board", 4);
        table.get("tfm").get("enum").get("shamanObject").set("ball", 6);
        table.get("tfm").get("enum").get("shamanObject").set("trampoline", 7);
        table.get("tfm").get("enum").get("shamanObject").set("anvil", 10);
        table.get("tfm").get("enum").get("shamanObject").set("cannon", 17);
        table.get("tfm").get("enum").get("shamanObject").set("bomb", 23);
        table.get("tfm").get("enum").get("shamanObject").set("bluePortal", 26);
        table.get("tfm").get("enum").get("shamanObject").set("orangePortal", 27);
        table.get("tfm").get("enum").get("shamanObject").set("balloon", 28);
        table.get("tfm").get("enum").get("shamanObject").set("blueBalloon", 28);
        table.get("tfm").get("enum").get("shamanObject").set("redBalloon", 29);
        table.get("tfm").get("enum").get("shamanObject").set("greenBalloon", 30);
        table.get("tfm").get("enum").get("shamanObject").set("yellowBalloon", 31);
        table.get("tfm").get("enum").get("shamanObject").set("rune", 32);
        table.get("tfm").get("enum").get("shamanObject").set("chicken", 33);
        table.get("tfm").get("enum").get("shamanObject").set("snowBall", 34);
        table.get("tfm").get("enum").get("shamanObject").set("cupidonArrow", 35);
        table.get("tfm").get("enum").get("shamanObject").set("apple", 39);
        table.get("tfm").get("enum").get("shamanObject").set("sheep", 40);
        table.get("tfm").get("enum").get("shamanObject").set("littleBoardIce", 45);
        table.get("tfm").get("enum").get("shamanObject").set("littleBoardChocolate", 46);
        table.get("tfm").get("enum").get("shamanObject").set("iceCube", 54);
        table.get("tfm").get("enum").get("shamanObject").set("cloud", 57);
        table.get("tfm").get("enum").get("shamanObject").set("bubble", 59);
        table.get("tfm").get("enum").get("shamanObject").set("tinyBoard", 60);
        table.get("tfm").get("enum").get("shamanObject").set("companionCube", 61);
        table.get("tfm").get("enum").get("shamanObject").set("stableRune", 62);
        table.get("tfm").get("enum").get("shamanObject").set("balloonFish", 65);
        table.get("tfm").get("enum").get("shamanObject").set("longBoard", 67);
        table.get("tfm").get("enum").get("shamanObject").set("triangle", 68);
        table.get("tfm").get("enum").get("shamanObject").set("sBoard", 69);
        table.get("tfm").get("enum").get("shamanObject").set("paperPlane", 80);
        table.get("tfm").get("enum").get("shamanObject").set("rock", 85);
        table.get("tfm").get("enum").get("shamanObject").set("pumpkinBall", 89);
        table.get("tfm").get("enum").get("shamanObject").set("tombstone", 90);
        table.get("tfm").get("enum").get("shamanObject").set("paperBall", 95);
        table.get("tfm").get("enum").set("ground", new LuaTable());
        table.get("tfm").get("enum").get("ground").set("wood", 0);
        table.get("tfm").get("enum").get("ground").set("ice", 1);
        table.get("tfm").get("enum").get("ground").set("trampoline", 2);
        table.get("tfm").get("enum").get("ground").set("lava", 3);
        table.get("tfm").get("enum").get("ground").set("chocolate", 4);
        table.get("tfm").get("enum").get("ground").set("earth", 5);
        table.get("tfm").get("enum").get("ground").set("grass", 6);
        table.get("tfm").get("enum").get("ground").set("sand", 7);
        table.get("tfm").get("enum").get("ground").set("cloud", 8);
        table.get("tfm").get("enum").get("ground").set("water", 9);
        table.get("tfm").get("enum").get("ground").set("stone", 10);
        table.get("tfm").get("enum").get("ground").set("snow", 11);
        table.get("tfm").get("enum").get("ground").set("rectangle", 12);
        table.get("tfm").get("enum").get("ground").set("circle", 13);
        table.get("tfm").get("enum").get("ground").set("invisible", 14);
        table.get("tfm").get("enum").get("ground").set("web", 15);
        table.get("tfm").get("enum").get("ground").set("yellowGrass", 17);
        table.get("tfm").get("enum").get("ground").set("pinkGrass", 18);
        table.get("tfm").get("enum").get("ground").set("pinkGrass", 19);

        table.get("tfm").get("enum").set("particle", new LuaTable());
        table.get("tfm").get("enum").get("particle").set("whiteGlitter", 0);
        table.get("tfm").get("enum").get("particle").set("blueGlitter", 1);
        table.get("tfm").get("enum").get("particle").set("orangeGlitter", 2);
        table.get("tfm").get("enum").get("particle").set("cloud", 3);
        table.get("tfm").get("enum").get("particle").set("dullWhiteGlitter", 4);
        table.get("tfm").get("enum").get("particle").set("heart", 5);
        table.get("tfm").get("enum").get("particle").set("bubble", 6);
        table.get("tfm").get("enum").get("particle").set("tealGlitter", 9);
        table.get("tfm").get("enum").get("particle").set("spirit", 10);
        table.get("tfm").get("enum").get("particle").set("yellowGlitter", 11);
        table.get("tfm").get("enum").get("particle").set("ghostSpirit", 12);
        table.get("tfm").get("enum").get("particle").set("redGlitter", 13);
        table.get("tfm").get("enum").get("particle").set("waterBubble", 14);
        table.get("tfm").get("enum").get("particle").set("plus1", 15);
        table.get("tfm").get("enum").get("particle").set("plus10", 16);
        table.get("tfm").get("enum").get("particle").set("plus12", 17);
        table.get("tfm").get("enum").get("particle").set("plus14", 18);
        table.get("tfm").get("enum").get("particle").set("plus16", 19);
        table.get("tfm").get("enum").get("particle").set("meep", 20);
        table.get("tfm").get("enum").get("particle").set("redConfetti", 21);
        table.get("tfm").get("enum").get("particle").set("greenConfetti", 22);
        table.get("tfm").get("enum").get("particle").set("blueConfetti", 23);
        table.get("tfm").get("enum").get("particle").set("yellowConfetti", 24);
        table.get("tfm").get("enum").get("particle").set("diagonalRain", 25);
        table.get("tfm").get("enum").get("particle").set("curlyWind", 26);
        table.get("tfm").get("enum").get("particle").set("wind", 27);
        table.get("tfm").get("enum").get("particle").set("rain", 28);
        table.get("tfm").get("enum").get("particle").set("star", 29);
        table.get("tfm").get("enum").get("particle").set("littleRedHeart", 30);
        table.get("tfm").get("enum").get("particle").set("littlePinkHeart", 31);
        table.get("tfm").get("enum").get("particle").set("daisy", 32);
        table.get("tfm").get("enum").get("particle").set("bell", 33);
        table.get("tfm").get("enum").get("particle").set("projection", 35);
        table.get("tfm").get("enum").get("particle").set("egg", 34);
        table.get("tfm").get("enum").get("particle").set("mouseTeleportation", 36);
        table.get("tfm").get("enum").get("particle").set("shamanTeleportation", 37);
        table.get("tfm").get("enum").get("particle").set("lollipopConfetti", 38);
        table.get("tfm").get("enum").get("particle").set("yellowCandyConfetti", 39);
        table.get("tfm").get("enum").get("particle").set("pinkCandyConfetti", 40);

        table.get("tfm").set("get", new LuaTable());
        table.get("tfm").get("get").set("misc", new LuaTable());
        table.get("tfm").get("get").get("misc").set("apiVersion", "0.2");
        table.get("tfm").get("get").get("misc").set("transformiceVersion", "1." + Application.getSwfInfo().version);
        table.get("tfm").get("get").set("room", new LuaTable());
        table.get("tfm").get("get").get("room").set("name", this.room.getRoomName());
        table.get("tfm").get("get").get("room").set("community", this.room.getRoomCommunity());
        table.get("tfm").get("get").get("room").set("maxPlayers", this.room.getMaximumPlayers());
        table.get("tfm").get("get").get("room").set("passwordProtected", LuaBoolean.valueOf(!this.room.getRoomPassword().isEmpty()));
        table.get("tfm").get("get").get("room").set("currentMap", !this.room.getCurrentMap().mapXml.isEmpty() ? ("@" + this.room.getCurrentMap().mapCode) : String.valueOf(this.room.getCurrentMap().mapCode));
        table.get("tfm").get("get").get("room").set("mirroredMap", LuaBoolean.valueOf(this.room.getCurrentMap().isInverted));
        table.get("tfm").get("get").get("room").set("objectList", new LuaTable());
        table.get("tfm").get("get").get("room").set("playerList", this.room.getLuaPlayerList());

        table.get("tfm").set("exec", new LuaTable());
        table.get("tfm").get("exec").set("addBonus", new TFM_addBonus(this.room));
        table.get("tfm").get("exec").set("addConjuration", new TFM_addConjuration(this.room));
        table.get("tfm").get("exec").set("addImage", new TFM_addImage(this.room));
        table.get("tfm").get("exec").set("addJoint", new TFM_addJoint(this.room));
        table.get("tfm").get("exec").set("addNPC", new TFM_addNPC(this.room));
        table.get("tfm").get("exec").set("addPhysicObject", new TFM_addPhysicObject(this.room));
        table.get("tfm").get("exec").set("addShamanObject", new TFM_addShamanObject(this.room));
        table.get("tfm").get("exec").set("attachBalloon", new TFM_attachBalloon(this.room));
        table.get("tfm").get("exec").set("bindKeyboard", new SY_bindKeyboard(this.room));
        table.get("tfm").get("exec").set("changePlayerSize", new TFM_changePlayerSize(this.room));
        table.get("tfm").get("exec").set("chatMessage", new TFM_chatMessage(this.room));
        table.get("tfm").get("exec").set("disableAfkDeath", new TFM_disableAfkDeath(this.room));
        table.get("tfm").get("exec").set("disableAllShamanSkills", new TFM_disableAllShamanSkills(this.room));
        table.get("tfm").get("exec").set("disableAutoNewGame", new TFM_disableAutoNewGame(this.room));
        table.get("tfm").get("exec").set("disableAutoScore", new TFM_disableAutoScore(this.room));
        table.get("tfm").get("exec").set("disableAutoShaman", new TFM_disableAutoShaman(this.room));
        table.get("tfm").get("exec").set("disableAutoTimeLeft", new TFM_disableAutoTimeLeft(this.room));
        table.get("tfm").get("exec").set("disableDebugCommand", new TFM_disableDebugCommand(this.room));
        table.get("tfm").get("exec").set("disableMinimalistMode", new TFM_disableMinimalistMode(this.room));
        table.get("tfm").get("exec").set("disableMortCommand", new TFM_disableMortCommand(this.room));
        table.get("tfm").get("exec").set("disablePhysicalConsumables", new TFM_disablePhysicalConsumables(this.room));
        table.get("tfm").get("exec").set("disableWatchCommand", new TFM_disableWatchCommand(this.room));
        table.get("tfm").get("exec").set("displayParticle", new TFM_displayParticle(this.room));
        table.get("tfm").get("exec").set("TFM_executeChatCommand", new TFM_executeChatCommand(this.room));
        table.get("tfm").get("exec").set("explosion", new TFM_explosion(this.room));
        table.get("tfm").get("exec").set("freezePlayer", new TFM_freezePlayer(this.room));
        table.get("tfm").get("exec").set("getPlayerSync", new TFM_getPlayerSync(this.room));
        table.get("tfm").get("exec").set("giveCheese", new TFM_giveCheese(this.room));
        table.get("tfm").get("exec").set("giveConsumables", new TFM_giveConsumables(this.room));
        table.get("tfm").get("exec").set("giveMeep", new TFM_giveMeep(this.room));
        table.get("tfm").get("exec").set("giveTransformations", new TFM_giveTransformations(this.room));
        table.get("tfm").get("exec").set("kickPlayer", new TFM_kickPlayer(this.room));
        table.get("tfm").get("exec").set("killPlayer", new TFM_killPlayer(this.room));
        table.get("tfm").get("exec").set("linkMice", new TFM_linkMice(this.room));
        table.get("tfm").get("exec").set("lowerSyncDelay", new TFM_lowerSyncDelay(this.room));
        table.get("tfm").get("exec").set("moveObject", new TFM_moveObject(this.room));
        table.get("tfm").get("exec").set("movePhysicObject", new TFM_movePhysicObject(this.room));
        table.get("tfm").get("exec").set("movePlayer", new TFM_movePlayer(this.room));
        table.get("tfm").get("exec").set("newGame", new TFM_newGame(this.room));
        table.get("tfm").get("exec").set("playEmote", new TFM_playEmote(this.room));
        table.get("tfm").get("exec").set("playMusic", new TFM_playMusic(this.room));
        table.get("tfm").get("exec").set("playSound", new TFM_playSound(this.room));
        table.get("tfm").get("exec").set("playerVictory", new TFM_playerVictory(this.room));
        table.get("tfm").get("exec").set("removeBonus", new TFM_removeBonus(this.room));
        table.get("tfm").get("exec").set("removeCheese", new TFM_removeCheese(this.room));
        table.get("tfm").get("exec").set("removeImage", new TFM_removeImage(this.room));
        table.get("tfm").get("exec").set("removeJoint", new TFM_removeJoint(this.room));
        table.get("tfm").get("exec").set("removeMonster", new TFM_removeMonster(this.room));
        table.get("tfm").get("exec").set("removeObject", new TFM_removeObject(this.room));
        table.get("tfm").get("exec").set("removePhysicObject", new TFM_removePhysicObject(this.room));
        table.get("tfm").get("exec").set("respawnPlayer", new TFM_respawnPlayer(this.room));
        table.get("tfm").get("exec").set("setAieMode", new TFM_setAieMode(this.room));
        table.get("tfm").get("exec").set("setAutoMapFlipMode", new TFM_setAutoMapFlipMode(this.room));
        table.get("tfm").get("exec").set("setGameTime", new TFM_setGameTime(this.room));
        table.get("tfm").get("exec").set("setMonsterSpeed", new TFM_setMonsterSpeed(this.room));
        table.get("tfm").get("exec").set("setNameColor", new TFM_setNameColor(this.room));
        table.get("tfm").get("exec").set("setPlayerCollision", new TFM_setPlayerCollision(this.room));
        table.get("tfm").get("exec").set("setPlayerGravityScale", new TFM_setPlayerGravityScale(this.room));
        table.get("tfm").get("exec").set("setPlayerHealth", new TFM_setPlayerHealth(this.room));
        table.get("tfm").get("exec").set("setPlayerLook", new TFM_setPlayerLook(this.room));
        table.get("tfm").get("exec").set("setPlayerNightMode", new TFM_setPlayerNightMode(this.room));
        table.get("tfm").get("exec").set("setPlayerScore", new TFM_setPlayerScore(this.room));
        table.get("tfm").get("exec").set("setPlayerSync", new TFM_setPlayerSync(this.room));
        table.get("tfm").get("exec").set("setRoomMaxPlayers", new TFM_setRoomMaxPlayers(this.room));
        table.get("tfm").get("exec").set("setRoomPassword", new TFM_setRoomPassword(this.room));
        table.get("tfm").get("exec").set("setShaman", new TFM_setShaman(this.room));
        table.get("tfm").get("exec").set("setShamanMode", new TFM_setShamanMode(this.room));
        table.get("tfm").get("exec").set("setUIMapName", new UI_setMapName(this.room));
        table.get("tfm").get("exec").set("setUIShamanName", new UI_setShamanName(this.room));
        table.get("tfm").get("exec").set("setVampirePlayer", new TFM_setVampirePlayer(this.room));
        table.get("tfm").get("exec").set("setWorldGravity", new TFM_setWorldGravity(this.room));
        table.get("tfm").get("exec").set("snow", new TFM_snow(this.room));
        table.get("tfm").get("exec").set("spawnMonster", new TFM_spawnMonster(this.room));
        table.get("tfm").get("exec").set("stopMusic", new TFM_stopMusic(this.room));
        return table.get("tfm");
    }
}